name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: make validate

  test:
    strategy:
      fail-fast: false
      matrix:
        # Run tests across all platforms, to ensure developers
        # can use any environment to run basic tests.
        platform: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.platform }}
    needs: [ validate ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
  
    - run: make test

  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-12]
  
    runs-on: ${{ matrix.platform }}
    needs: [ validate ]

    steps:
    - name: Setup docker (MacOS only)
      if: runner.os == 'macos'
      run: |
        brew install docker
        colima start
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Test building images
      run: make test-image

    - name: E2E Tests
      run: make e2e
